import { Type } from "typebox";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import type { MemoryEngine, Scope } from "./types.ts";

const scope = Type.Optional(Type.Object({ kind: Type.Union([Type.Literal("global"), Type.Literal("user"), Type.Literal("organization"), Type.Literal("project"), Type.Literal("repository"), Type.Literal("workspace"), Type.Literal("branch"), Type.Literal("environment"), Type.Literal("session")]), value: Type.Optional(Type.String()) }));
const text = (value: unknown) => JSON.stringify(value, null, 2);

export function registerMemoryTools(pi: ExtensionAPI, engine: () => MemoryEngine, currentScope: () => Scope) {
	pi.registerTool({ name: "memory_retrieve", label: "Retrieve memory", description: "Retrieve bounded, durable memory relevant to a request.", parameters: Type.Object({ request: Type.String(), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 20 })), scope }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().retrieve({ request: params.request, limit: params.limit, scope: params.scope as Scope | undefined ?? currentScope() })) }] }; } });
	pi.registerTool({ name: "memory_inspect", label: "Inspect memory", description: "Inspect one durable memory by id.", parameters: Type.Object({ id: Type.String() }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().inspect(params.id) ?? { error: "memory not found" }) }] }; } });
	pi.registerTool({ name: "memory_search_sessions", label: "Search memory sessions", description: "Search bounded, redacted stored session digests.", parameters: Type.Object({ query: Type.String(), limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 50 })) }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().searchSessions(params.query, params.limit)) }] }; } });
	pi.registerTool({ name: "memory_propose", label: "Propose memory", description: "Create an auditable candidate; it is not durable until explicit consolidation.", parameters: Type.Object({ type: Type.Union([Type.Literal("preference"), Type.Literal("fact"), Type.Literal("constraint"), Type.Literal("decision"), Type.Literal("correction"), Type.Literal("lesson"), Type.Literal("procedure"), Type.Literal("observation")]), statement: Type.String(), rationale: Type.String(), confidence: Type.Number({ minimum: 0, maximum: 1 }), scope, suggestedAction: Type.Optional(Type.Union([Type.Literal("create"), Type.Literal("defer"), Type.Literal("reject"), Type.Literal("update"), Type.Literal("forget")])), targetMemoryId: Type.Optional(Type.String()) }), async execute(_id, params) { const candidate = await engine().propose({ ...params, scope: params.scope as Scope | undefined ?? currentScope(), sourceSessionId: "explicit-tool", evidence: [], suggestedAction: params.suggestedAction ?? "create" }); return { content: [{ type: "text", text: text(candidate) }] }; } });
	pi.registerTool({ name: "memory_forget", label: "Forget memory", description: "Propose an auditable forget action; it takes effect only after consolidation.", parameters: Type.Object({ id: Type.String(), reason: Type.String() }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().forget(params.id, params.reason)) }] }; } });
	pi.registerTool({ name: "memory_extract", label: "Extract memory candidates", description: "Run model-assisted extraction from stored redacted session evidence.", parameters: Type.Object({ sessionId: Type.Optional(Type.String()) }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().runExtraction(params.sessionId)) }] }; } });
	pi.registerTool({ name: "memory_consolidate", label: "Consolidate memories", description: "Explicitly consolidate pending candidates into durable memory.", parameters: Type.Object({ limit: Type.Optional(Type.Integer({ minimum: 1, maximum: 200 })) }), async execute(_id, params) { return { content: [{ type: "text", text: text(await engine().runConsolidation(params.limit)) }] }; } });
}

